### ISSUE TITLE
Bugs in multiline thing handling

### ISSUE THREAD

**Issue by whcrg** [aluguest/ical-easy-reader#2]
Nice base for simple calendar to webpage integration! 

Found bugs in multiline handling! Here is what seems to work:

Original: iCalEasyReader.php
```
// There are cases like "ATTENDEE" that may take several lines.
				if ( !in_array( $line[0], [" ", "\t"] ) And strpos( ':', $line ) === false )
				{
					$r = current($lines);
					$concatenar = next($lines);
					while ( $concatenar And in_array( $concatenar[0], [" ", "\t"] ) )
					{
						$r .= substr($concatenar, 1);
						$concatenar = next($lines);
					}
					prev($lines);
					if ($r !== $line )
						$line = $r;
				}
```

Proposed fix:
```
// There are cases like "ATTENDEE" that may take several lines.
				if ( in_array( $line[0], [" ", "\t"] )) //And strpos( ':', $line ) === false )
// the negation here was a mistake!!?
// ":" cannot be used as a identifier of new field because it would break links! ("http:"...). Works fine without.
				{
					$r = current($lines);
					$concatenar = next($lines);
					while ( $concatenar And in_array( $concatenar[0], [" ", "\t"] ) )
					{
						$r .= substr($concatenar, 1);
						$concatenar = next($lines);
					}
					prev($lines);
					if ($r !== $line )
						$line = $r;
				}
```

**Comment by matiasperrone** [comment]
Hi! can you provide a PR?

**Comment by BearlyDoug** [comment]
I came across this with DESCRIPTION, as well, Matias. I am happy to provide you with an ICS file, privately, but here are two examples:

`ATTENDEE;CN="Ian Reyes";RSVP=TRUE;PARTSTAT=ACCEPTED:mailto:ireyes@richmondd
	iocese.org
ATTENDEE;CN="Daniel DeHart (ddehart@DOMAINREMOVED.com)";RSVP=TRUE:mailto:
	ddehart@DOMAINREMOVED.com
ATTENDEE;CN="Arcel Dullas";RSVP=TRUE;PARTSTAT=ACCEPTED:mailto:adullas@DOMAI
	NREMOVED.com
ATTENDEE;CN="Eric Sund (esund@DOMAINREMOVED.com)";RSVP=TRUE;PARTSTAT=ACCE
	PTED:mailto:esund@DOMAINREMOVED.com`

`DESCRIPTION:Since I have a good grasp of what the tech needs are for these 
	two churches\, a quick meeting so that we can lay down the ground work for
	 Daniel's visit to St. Mary's and St. Francis ahead of time.\n\nConfirmed 
	things we know they'll need:\n* Better WAN/LAN set up\n* Dropbox\n* Conver
	sion to Office 365 Email\n* Desktops (2-3 systems in each location)\n* 1 L
	aptop for Father Carlos (cost split equally between both churches)\n* Dock
	ing station set up at each location for Father Carlos' laptop\n* Telephony
	 needs\n *Security needs (maybe)?\n\nSt. Francis has Office 2019 Standard 
	license(s) already. Not sure of how many licenses\, though. St. Mary's doe
	s not. Will need it for each desktop.\n`

**Comment by BearlyDoug** [comment]
[Broken ICS Info.txt](https://github.com/aluguest/ical-easy-reader/files/4496550/Broken.ICS.Info.txt)

**Comment by BearlyDoug** [comment]
Some more examples, plus another concern: The DESCRIPTION and the X-ALT-DESC values can also contain HTML (especially when copy/pasted from MS Word or MS Excel or some kind of fancy WYSIWYG interface.  You'll probably want to htmlentities($value, ENT_QUOTES) those items.

[Broken ICS Info2.txt](https://github.com/aluguest/ical-easy-reader/files/4496638/Broken.ICS.Info2.txt)

**Comment by matiasperrone** [comment]
Hi! I don't agree with your solution, but it's true that ":" may be included in the content... I'll try to fix this, before monday.

**Comment by BearlyDoug** [comment]
@matiasperrone, if it helps any, his solution doesn't help with my issues (you can see it in action from the info I sent earlier).

**Comment by matiasperrone** [comment]
Check the new version please!
